"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import datetime
import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-bgw5xs9677mf-ckhzyife2ntbofffj9*e#fp9u_d3*9pekm+fc'
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['194.67.86.225', 'localhost', '127.0.0.1', '0.0.0.0', 'backend', 'consultplacetest.sytes.net']

# ALLOWED_HOSTS = ['*', '194.67.86.225', '127.0.0.1', 'localhost', 'consultplace.sytes.net']
INTERNAL_IPS = ['127.0.0.1']

AUTH_USER_MODEL = 'account.CustomUser'
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',

    'rest_framework',
    'dj_rest_auth',
    'rest_framework_simplejwt',
    # 'modeltranslation',
    'drf_yasg',
    'account',
    'django_filters',
    'django_extensions',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',

]

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'db'),
            'USER': os.getenv('POSTGRES_USER', 'db'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', ''),
            'PORT': os.getenv('DB_PORT', 5432)
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# # settings.py
# CELERY_BROKER_URL = 'redis://redis:6380/0'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_DIR = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [STATIC_DIR]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 'data' is my media folder
MEDIA_URL = 'media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=365),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'TOKEN_MODEL': None,
}

REST_USE_JWT = True
JWT_AUTH_COOKIE = 'jwt-auth'
JWT_AUTH_REFRESH_COOKIE = 'refresh'
JWT_AUTH_SECURE_COOKIE = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "CONSULTPLACE Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "CONSULTPLACE",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "CONSULTPLACE",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "/logo_ConsultPlace.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "/logo_ConsultPlace.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": "/logo_ConsultPlace.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "/logo_ConsultPlace.png",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "/logo_ConsultPlace.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the  ConsultPlace",

    # Copyright on the footer
    "copyright": "CONSULTPLACE",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    "search_model": ["auth.User", "auth.Group"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": "get_avatar_url",

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "products"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "auth": [
            {
                "name": _("Send newsletter"),
                "url": "/api/students/students/",  # Используем абсолютный URL
                "icon": "fas fa-comments",
                "permissions": ["chat.view"]
            },
        ],
        # "Персональные данные":
        #     {
        #         "icon": "fas fa-user",
        #         "children": [
        #             {"model": "account.Student", "name": "Студенты"},
        #             {"model": "account.University", "name": "ВУЗы"},
        #             {"model": "account.UserInterestsThird", "name": "Цели"}
        #         ]
        #     }

        # "account": [
        #     {
        #         "name": "Профессиональная сфера интересов",
        #         "url": "api/students/user_interests_first/",
        #         "icon": "fas fa-user"
        #     },
        #     {
        #         "name": "Интересующие вас ниши",
        #         "url": "api/students/user_interests_second/",
        #         "icon": "fas fa-user"
        #     },
        #     {
        #         "name": "Цели",
        #         "url": "api/students/user_interests_third/",
        #         "icon": "fas fa-user"
        #     },
        #     {
        #         "name": "Образование",
        #         "url": "api/students/user_before_university/",
        #         "icon": "fas fa-user"
        #     },
        #     {
        #         "name": "ВУЗ",
        #         "url": "api/students/user_university/",
        #         "icon": "fas fa-user"
        #     },
        #     {
        #         "name": "Курс",
        #         "url": "api/students/courses/",
        #         "icon": "fas fa-user"
        #     },
        # ]
    },
    # "order_with_respect_to": [
    #     {
    #         "section": "Специалисты",
    #         "models": [
    #             "account.Student",
    #             "account.CustomUser",
    #             "account.StudentCV",
    #             "account.University",
    #             "account.BeforeUniversity",
    #             "account.StudentPortfolio",
    #             "account.UserInterestsFirst",
    #             "account.UserInterestsSecond",
    #             "account.UserInterestsThird",
    #             "account.Course",
    #             "account.Chapter",
    #             "account.UnderSection"
    #         ]
    #     },

    #     {
    #         "section": "Проекты",
    #         "models": [
    #             "account.DataKnowledge",
    #             "account.DataKnowledgeFree",
    #             "account.DataKnowledgeGeneral",
    #             "account.GroupStudent",
    #             "account.Project",
    #             "account.TaskStudent",
    #             "account.TaskGroup",
    #             "account.Mailing",
    #             "account.File",
    #             "account.ProjectInvitation",
    #             "account.StudentInvitation"
    #         ]
    #     },

    #     {
    #         "section": "Регистрация",
    #         "models": [
    #             "account.TestTask",
    #             "account.TestTaskEvaluation",
    #             "account.Orders",
    #             "account.Subscription"
    #         ]
    #     },
    # ],
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "account.interest": "fas fa-heart",
        "account.speciality": "fas fa-book",
        "account.user": "fas fa-user",
        # "Специалисты": "fas fa-folder-open",
        # "account.Student": "fas fa-file",
        # "account.CustomUser": "fas fa-file",
        # "account.StudentCV": "fas fa-file",
        # "account.University": "fas fa-file",
        # "account.BeforeUniversity": "fas fa-file",
        # "account.StudentPortfolio": "fas fa-file",
        # "account.UserInterestsFirst": "fas fa-file",
        # "account.UserInterestsSecond": "fas fa-file",
        # "account.UserInterestsThird": "fas fa-file",
        # "account.Course": "fas fa-file",
        # "account.Chapter": "fas fa-file",
        # "account.UnderSection": "fas fa-file",
        # "Проекты": "fas fa-folder-open",
        # "account.DataKnowledge": "fas fa-file",
        # "account.DataKnowledgeFree": "fas fa-file",
        # "account.DataKnowledgeGeneral": "fas fa-file",
        # "account.GroupStudent": "fas fa-file",
        # "account.Project": "fas fa-file",
        # "account.TaskStudent": "fas fa-file",
        # "account.TaskGroup": "fas fa-file",
        # "account.Mailing": "fas fa-file",
        # "account.File": "fas fa-file",
        # "account.ProjectInvitation": "fas fa-file",
        # "account.StudentInvitation": "fas fa-file",
        # "Регистрация": "fas fa-folder-open",
        # "account.TestTask": "fas fa-file",
        # "account.TestTaskEvaluation": "fas fa-file",
        # "account.Orders": "fas fa-file",
        # "account.Subscription": "fas fa-file",

    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,

    # "UI_TWEAKS": {
    #     "navbar_small_text": False,
    #     "footer_small_text": False,
    #     "body_small_text": False,
    #     "brand_small_text": False,
    #     "brand_colour": False,
    #     "accent": "accent-primary",
    #     "navbar": "navbar-white navbar-light",
    #     "no_navbar_border": False,
    #     "navbar_fixed": False,
    #     "layout_boxed": False,
    #     "footer_fixed": False,
    #     "sidebar_fixed": False,
    #     "sidebar": "sidebar-dark-primary",
    #     "sidebar_nav_small_text": False,
    #     "sidebar_disable_expand": False,
    #     "sidebar_nav_child_indent": False,
    #     "sidebar_nav_compact_style": False,
    #     "sidebar_nav_legacy_style": False,
    #     "sidebar_nav_flat_style": False,
    #     "theme": "default",
    #     "dark_mode_theme": None,
    #     "button_classes": {
    #         "primary": "btn-primary",
    #         "secondary": "btn-secondary",
    #         "info": "btn-info",
    #         "warning": "btn-warning",
    #         "danger": "btn-danger",
    #         "success": "btn-success"
    #     },
    #     "actions_sticky_top": False
    # },

}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    # "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

# LANGUAGES = [
#     ('en', _('English')),
#     ('es', _('Español')),
#     ('ru', _('Русский')),
# ]

# ADMIN_LANGUAGE_REDIRECT_LANGUAGES = ['en', 'es', 'ru']
# ADMIN_LANGUAGE_REDIRECT_EXCLUDE_APPS = []
# # Активируем временную метку для языковых каталогов
# LOCALE_PATHS = [
#     os.path.join(BASE_DIR, 'locale'),
# ]

# MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'  # Язык по умолчанию

# MODELTRANSLATION_LANGUAGES = ('en', 'es', 'ru')  # Список языков

# MODELTRANSLATION_FALLBACK_LANGUAGES = {'default': ('en',)}

# TRANSLATABLE_MODEL_MODULES = []

GRAPH_MODELS = {
    'all_applications': True,
    'group_models': True,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
            'formatter': 'verbose'
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Указывайте дополнительные логгеры для ваших приложений
        'account': {  # замените 'myapp' на название вашего приложения
            'handlers': ['file', 'console'],
            'level': 'WARNING',
        },
    },
}

CELERY_BROKER_URL = 'redis://194.67.86.225:6379/1'
CELERY_RESULT_BACKEND = 'redis://194.67.86.225:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
CSRF_TRUSTED_ORIGINS = [
    'https://consultplacetest.sytes.net',
]
