# Generated by Django 4.2.3 on 2024-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtask',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='project_cost',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='start_date',
        ),
        migrations.AddField(
            model_name='testtask',
            name='task_duration',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на задание'),
        ),
    ]
