# Generated by Django 4.2.3 on 2024-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_testtask_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='task_duration',
            field=models.IntegerField(blank=True, max_length=120, null=True, verbose_name='Срок выполнения (дни)'),
        ),
    ]
