# Generated by Django 4.2.3 on 2024-04-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_testtask_grade_student_test_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataknowledgegeneral',
            name='files',
            field=models.ManyToManyField(blank=True, to='account.file', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(choices=[('Не определен', 'Default'), ('Студент', 'Student'), ('Стажер', 'Trainee'), ('Аналитик', 'Analyst')], default='Default', max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='task_duration',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Срок выполнения (дни)'),
        ),
        migrations.CreateModel(
            name='TessTaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(choices=[('Да', 'Yes'), ('Нет', 'No')], default=False)),
                ('score', models.IntegerField(choices=[(0, 'В работе'), (1, 'Предложить обучение'), (2, 'Предложить стажировку'), (3, 'Штат аналитиков')], default=0, verbose_name='Оценка')),
                ('comment', models.TextField(max_length=500)),
                ('assigned_tesstask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.testtask', verbose_name='Предложенная задача')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка тестового',
                'verbose_name_plural': 'Оценки тестовых',
            },
        ),
    ]
