# Generated by Django 4.2.3 on 2024-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_dataknowledgegeneral_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataknowledgegeneral',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Прочие ссылки'),
        ),
        migrations.AlterField(
            model_name='dataknowledgegeneral',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Видео-материалы'),
        ),
    ]
