# Generated by Django 4.2.3 on 2024-04-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_dataknowledgegeneral_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TessTaskEvaluation',
            new_name='TestTaskEvaluation',
        ),
    ]
