# Generated by Django 4.2.3 on 2024-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_tesstaskevaluation_testtaskevaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtask',
            options={'verbose_name': 'Задача тестовое', 'verbose_name_plural': 'Задачи тестовые'},
        ),
        migrations.AddField(
            model_name='testtask',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название задания'),
        ),
        migrations.AddField(
            model_name='testtaskevaluation',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Выполненное задание'),
        ),
        migrations.AlterField(
            model_name='dataknowledge',
            name='files',
            field=models.ManyToManyField(blank=True, to='account.file', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='dataknowledge',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Прочие ссылки'),
        ),
        migrations.AlterField(
            model_name='dataknowledge',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Видео-материалы'),
        ),
        migrations.AlterField(
            model_name='dataknowledgefree',
            name='files',
            field=models.ManyToManyField(blank=True, to='account.file', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='dataknowledgefree',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Прочие ссылки'),
        ),
        migrations.AlterField(
            model_name='dataknowledgefree',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Видео-материалы'),
        ),
    ]
