# Generated by Django 4.2.3 on 2024-04-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_testtask_options_testtask_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtaskevaluation',
            old_name='assigned_tesstask',
            new_name='assigned_testtask',
        ),
    ]
