# Generated by Django 4.2.3 on 2024-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_testtaskevaluation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskevaluation',
            name='is_completed',
            field=models.CharField(blank=True, choices=[('Да', 'Yes'), ('Нет', 'No')], max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
