# Generated by Django 4.2.3 on 2024-04-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_testtaskevaluation_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskevaluation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент'),
        ),
    ]
