# Generated by Django 4.2.3 on 2024-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_testtaskevaluation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaskevaluation',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Телеграм ID User'),
        ),
    ]
