# Generated by Django 4.2.3 on 2024-04-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_testtaskevaluation_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskevaluation',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент'),
        ),
    ]
