# Generated by Django 4.2.3 on 2024-04-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_testtaskevaluation_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskevaluation',
            name='is_completed',
            field=models.CharField(choices=[('Да', 'Yes'), ('Нет', 'No')], default='Нет', max_length=50, verbose_name='Статус'),
        ),
    ]
