# Generated by Django 4.2.3 on 2024-05-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_testtaskevaluation_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersstudent',
            options={'verbose_name': 'Ответ специалиста', 'verbose_name_plural': 'Ответы специалистов'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterModelOptions(
            name='studentcv',
            options={'verbose_name': 'Резюме специалиста', 'verbose_name_plural': 'Резюме специалистов'},
        ),
        migrations.AlterModelOptions(
            name='studentportfolio',
            options={'verbose_name': 'Портфолио специалиста', 'verbose_name_plural': 'Портфолио специалиста'},
        ),
        migrations.AlterModelOptions(
            name='taskstatusstudent',
            options={'verbose_name': 'Статус задачи специалиста', 'verbose_name_plural': 'Статус задач специалистов'},
        ),
        migrations.AlterModelOptions(
            name='taskstudent',
            options={'verbose_name': 'Задача специалиста по проекту', 'verbose_name_plural': 'Задача специалистов по проекту'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='account.student', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.student', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='studentcv',
            name='file',
            field=models.FileField(upload_to='student_cv', verbose_name='Резюме специалиста'),
        ),
        migrations.AlterField(
            model_name='studentcv',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='studentportfolio',
            name='file',
            field=models.FileField(upload_to='student_cv', verbose_name='Портфолио специалиста'),
        ),
        migrations.AlterField(
            model_name='studentportfolio',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='assigned_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='account.student', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='testtaskevaluation',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Специалист'),
        ),
    ]
