# Generated by Django 4.2.3 on 2024-05-07 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_answersstudent_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskevaluation',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], verbose_name='Срок подписки (мес)')),
                ('expiration_timestamp', models.BigIntegerField(verbose_name='Время окончания подписки (таймстамп)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscription', to='account.student')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='account.subscription'),
        ),
    ]
