# Generated by Django 4.2.3 on 2024-05-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_testtaskevaluation_comment_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_timestamp',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Время окончания подписки (таймстамп)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscription', to='account.student', verbose_name='Пользователь'),
        ),
    ]
