# Generated by Django 4.2.3 on 2024-05-13 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_taskstudent_task_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstudent',
            name='deadline_compliance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Соблюдение дедлайнов'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='intricacy_coefficient',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Коэффициент сложности'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='manager_recommendation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Рекомендация менеджера'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='personal_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Оценка по проекту'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='task_credits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Кредиты'),
        ),
    ]
