# Generated by Django 4.2.3 on 2024-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_taskstudent_deadline_compliance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='student',
        ),
        migrations.AddField(
            model_name='mailing',
            name='student',
            field=models.ManyToManyField(related_name='mailings', to='account.student', verbose_name='Специалисты'),
        ),
    ]
