# Generated by Django 4.2.3 on 2024-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_mailing_student_mailing_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(choices=[(0, 'Not specified'), (1, 'Student'), (2, 'Trainee'), (3, 'Analyst')], default=0, max_length=50, verbose_name='Должность'),
        ),
    ]
