# Generated by Django 4.2.3 on 2024-06-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_student_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.IntegerField(choices=[(0, 'Not specified'), (1, 'Student'), (2, 'Trainee'), (3, 'Analyst')], default=0, verbose_name='Должность'),
        ),
    ]
