# Generated by Django 4.2.3 on 2024-06-14 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_student_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaskevaluation',
            name='date_accepted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
    ]
