# Generated by Django 4.2.3 on 2024-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_answersstudent_user_remove_student_test_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersstudent',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='answersstudent',
            name='status',
            field=models.CharField(choices=[('Не определено', 'Not specified'), ('Предложить правки', 'Suggest edits'), ('Отправить фидбэк', 'Submit feedback')], default='Free', max_length=50, verbose_name='Статус проверки'),
        ),
    ]
