# Generated by Django 4.2.3 on 2024-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_answersstudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersstudent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not specified'), (1, 'Suggest edits'), (2, 'Submit feedback')], default=0, verbose_name='Статус проверки'),
        ),
    ]
