# Generated by Django 4.2.3 on 2024-08-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_answersstudent_deadline_compliance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersstudent',
            name='answer',
        ),
        migrations.AddField(
            model_name='answersstudent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taskstudent', verbose_name='Задача студента'),
        ),
    ]
