# Generated by Django 4.2.3 on 2024-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_remove_taskstudent_task_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinvitation',
            options={'verbose_name': 'Приглашение в проект', 'verbose_name_plural': 'Приглашение в проекты'},
        ),
        migrations.AlterModelOptions(
            name='studentinvitation',
            options={'verbose_name': 'Приглашение студента', 'verbose_name_plural': 'Приглашение студентов'},
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Телеграм ID User'),
        ),
    ]
